
require('super-cheat/lib')
require('super-cheat/cheat-item')
require('super-cheat/must-die-turret')
// require('super-cheat/enemys-cannot-move')
// require('super-cheat/enemys-control')
// require('super-cheat/enemys-no-damage')
// require('super-cheat/enemys-remove')
require('super-cheat/invincible-core')
require('super-cheat/static-drill')
require('super-cheat/invincible-force-projector')
// require('super-cheat/invincible-ship')
require('super-cheat/invincible-simple-blocks')
require('super-cheat/next-wave')
// require('super-cheat/quantum-launchpad')
require('super-cheat/adjustable-overdrive-projector')
